import type { MetadataRoute } from "next";

/**
 * /robots.txt — generated by Next.js from this file.
 *
 * Public marketing pages are crawlable; the authenticated app, API,
 * auth-flow pages and customer-scoped token routes are disallowed (they
 * either redirect to /login for anonymous crawlers or expose nothing
 * useful to index). The sitemap is advertised so crawlers find the
 * canonical marketing URLs.
 *
 * NOTE: this route is also excluded from the auth middleware matcher
 * (see middleware.ts) so it is served publicly instead of 307-redirecting
 * to /login.
 */

const BASE = process.env.NEXT_PUBLIC_APP_URL ?? "https://crewflow.uk";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: [
          "/admin",
          "/api/",
          "/dashboard",
          "/login",
          "/signup",
          "/check-email",
          "/onboarding",
          "/access-pending",
          "/q/",
          "/customer-portal/",
          "/payment/",
        ],
      },
    ],
    sitemap: `${BASE}/sitemap.xml`,
    host: BASE,
  };
}
