import type { MetadataRoute } from "next";

/**
 * /sitemap.xml — generated by Next.js from this file.
 *
 * Lists only the genuinely public, indexable marketing pages. Everything
 * else (authenticated app, auth flow, token-scoped routes) is intentionally
 * omitted and disallowed in robots.ts.
 *
 * NOTE: this route is also excluded from the auth middleware matcher
 * (see middleware.ts) so it is served publicly instead of 307-redirecting
 * to /login.
 */

const BASE = process.env.NEXT_PUBLIC_APP_URL ?? "https://crewflow.uk";

export default function sitemap(): MetadataRoute.Sitemap {
  const lastModified = new Date();
  return [
    {
      url: `${BASE}/`,
      lastModified,
      changeFrequency: "weekly",
      priority: 1,
    },
    {
      url: `${BASE}/privacy`,
      lastModified,
      changeFrequency: "yearly",
      priority: 0.3,
    },
    {
      url: `${BASE}/terms`,
      lastModified,
      changeFrequency: "yearly",
      priority: 0.3,
    },
  ];
}
