import Link from "next/link";

/**
 * Friendly fallback for invalid or expired share links — used by the
 * public quote portal (/q/[token]) and the customer portal
 * (/customer-portal/[token]).
 *
 * Goal: never show a bare 404 to a customer following a contractor's
 * share link. Customers don't know what a 404 means; they DO know that
 * a link they were sent didn't work. This page acknowledges that, tells
 * them why (link's been rotated or the quote was withdrawn), and gives
 * them four next steps:
 *
 *   1. Wait for / ask the contractor for a new link
 *   2. Phone the contractor (if we know their number)
 *   3. Email the contractor (if we know their email)
 *   4. Return to the CrewFlow home page
 */

type ContractorContact = {
  name?: string | null;
  phone?: string | null;
  email?: string | null;
};

export function InvalidLinkPage({
  kind,
  contractor,
}: {
  /** Which surface failed — drives copy + the page title. */
  kind: "quote" | "portal";
  /** Best-effort contractor contact info, when we have it. */
  contractor?: ContractorContact;
}) {
  const title =
    kind === "quote"
      ? "This quote link isn't available"
      : "This portal link isn't available";

  const body =
    kind === "quote"
      ? "Quote links can expire, be replaced when the contractor rotates them, or be removed if the quote was withdrawn or hasn't been approved yet."
      : "Portal links can be regenerated by the contractor at any time — when that happens, the previous link stops working. The most recent link in their last email or message is the one that's live.";

  const hasName = !!contractor?.name;
  const hasPhone = !!contractor?.phone;
  const hasEmail = !!contractor?.email;

  return (
    <div className="min-h-screen bg-slate-100 px-4 py-12">
      <div className="mx-auto max-w-lg space-y-6">
        <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
          <div className="border-b border-slate-200 bg-slate-50 px-6 py-4">
            <p className="text-xs font-medium uppercase tracking-wide text-slate-500">
              Link expired or invalid
            </p>
            <h1 className="mt-1 text-xl font-bold text-slate-900">{title}</h1>
          </div>
          <div className="space-y-5 px-6 py-6 text-sm text-slate-700">
            <p>{body}</p>

            <div>
              <h2 className="text-xs font-semibold uppercase tracking-wide text-slate-500">
                What to do next
              </h2>
              <ol className="mt-2 list-decimal space-y-2 pl-5 text-slate-700">
                <li>
                  <strong className="text-slate-900">Request a new link.</strong>{" "}
                  {hasName ? `Ask ${contractor!.name}` : "Reply to the original email or message"}{" "}
                  for the latest share link. The old one is no longer valid.
                </li>
                <li>
                  <strong className="text-slate-900">Contact the company directly</strong> using the
                  details below.
                </li>
              </ol>
            </div>

            {hasName || hasPhone || hasEmail ? (
              <div className="rounded-xl border border-slate-200 bg-slate-50 px-4 py-3">
                <h2 className="text-xs font-semibold uppercase tracking-wide text-slate-500">
                  Contact{hasName ? ` ${contractor!.name}` : " the company"}
                </h2>
                <dl className="mt-2 space-y-1.5 text-sm">
                  {hasPhone ? (
                    <div className="flex items-center justify-between gap-3">
                      <dt className="text-slate-500">Phone</dt>
                      <dd>
                        <a
                          href={`tel:${contractor!.phone}`}
                          className="font-medium text-slate-900 hover:text-slate-700"
                        >
                          {contractor!.phone}
                        </a>
                      </dd>
                    </div>
                  ) : null}
                  {hasEmail ? (
                    <div className="flex items-center justify-between gap-3">
                      <dt className="text-slate-500">Email</dt>
                      <dd>
                        <a
                          href={`mailto:${contractor!.email}`}
                          className="font-medium text-slate-900 hover:text-slate-700"
                        >
                          {contractor!.email}
                        </a>
                      </dd>
                    </div>
                  ) : null}
                </dl>
              </div>
            ) : (
              <div className="rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-xs text-slate-600">
                We don&apos;t have public contact info for whoever sent this
                link. Check the email or text you received it in for their
                phone number or address.
              </div>
            )}

            <div className="flex flex-wrap gap-2 pt-2">
              <Link
                href="/"
                className="rounded-md bg-slate-900 px-4 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-slate-800"
              >
                Return home
              </Link>
            </div>
          </div>
        </div>

        <p className="text-center text-xs text-slate-600">
          Powered by CrewFlow · For contractors who&apos;d rather be on the
          tools than at a desk.
        </p>
      </div>
    </div>
  );
}
