import Link from "next/link";
import { whatsAppHref } from "@/lib/phone";
import {
  buildAlertsSnapshot,
  getOwnerContactsForOrgs,
  type OwnerContact,
} from "@/server/services/hq-alerts-snapshot";
import {
  runAlertRules,
  sortAlerts,
  filterAlerts,
  applyStateToAlerts,
  pickActionCentre,
  ALERT_SEVERITIES,
  ALERT_SORTS,
  ALERT_SORT_LABELS,
  SEVERITY_LABEL,
  THRESHOLDS,
  type Alert,
  type AlertSeverity,
  type AlertSort,
  type AlertWithState,
} from "@/lib/hq/alert-rules";
import {
  markAlertRead,
  markAlertResolved,
  snoozeAlert,
  reopenAlert,
} from "./actions";
import { ClientConfirmForm } from "../_client-confirm";
import {
  Alert as AlertBanner,
  AnimatedNumber,
  Badge,
  Button,
  ButtonLink,
  EmptyState,
  GlowHeader,
  Input,
  Select,
  StatTile,
  Surface,
  type Accent,
} from "@/components/ui";

/** Dark-surface accent per severity (mirrors the legacy light pill map). */
const SEVERITY_ACCENT: Record<AlertSeverity, Accent> = {
  critical: "rose",
  warning: "amber",
  info: "sky",
};

/**
 * Alerts + AI COO — HQ-5.
 *
 * Single place that surfaces every customer who needs attention,
 * generated by a deterministic rules engine (lib/hq/alert-rules.ts).
 * No LLM — pure rule firings against the existing data.
 *
 * Layout:
 *   1. AI COO panel at the top — "Today needs attention" — picks
 *      the top 3 critical/warning alerts deduped by org.
 *   2. KPI tiles — open critical / open warning / unread / resolved 7d.
 *   3. Filter bar — severity / search / sort / show resolved.
 *   4. List of alerts. Each card carries the directive's full
 *      action set: Call · Email · WhatsApp · Open customer ·
 *      Mark resolved · Snooze · Mark read.
 *
 * Auto-archive: resolved alerts disappear from the default view.
 * The list filters where resolved_at IS NULL unless ?show=resolved.
 *
 * Future-compat: LLM rerankers swap in at pickActionCentre without
 * changing the surrounding page. Channel dispatchers (email /
 * WhatsApp / SMS) iterate the same alert list — no schema work.
 */

type SP = Promise<{
  q?: string;
  severity?: string;
  sort?: string;
  show?: string;
  saved?: string;
  error?: string;
}>;

export default async function HqAlertsPage({
  searchParams,
}: {
  searchParams: SP;
}) {
  const sp = await searchParams;
  const q = (sp.q ?? "").trim();
  const severity = (sp.severity ?? "all") as AlertSeverity | "all";
  const sort = (ALERT_SORTS.includes(sp.sort as AlertSort)
    ? sp.sort
    : "severity") as AlertSort;
  const showResolved = sp.show === "resolved";

  const { snapshot, states } = await buildAlertsSnapshot();
  const baseAlerts = runAlertRules(snapshot);
  const withState = applyStateToAlerts(baseAlerts, states, snapshot.now);

  // Visible set: drop snoozed + resolved unless ?show=resolved.
  const visible = withState.filter((a) => {
    if (a.snoozed) return showResolved;
    if (a.resolved) return showResolved;
    return true;
  });

  const filtered = filterAlerts(visible, { severity, q });
  const sorted = sortAlerts(filtered, sort);

  // AI COO panel — operates on the full visible set, not the
  // filtered one (so the picker doesn't disappear when you search).
  const actionCentre = pickActionCentre(visible);

  // KPIs computed against the full alert set (not the visible
  // filter) so the operator sees system-wide truth.
  const openCritical = withState.filter(
    (a) => a.severity === "critical" && !a.resolved && !a.snoozed,
  ).length;
  const openWarning = withState.filter(
    (a) => a.severity === "warning" && !a.resolved && !a.snoozed,
  ).length;
  const unread = withState.filter((a) => a.unread && !a.snoozed && !a.resolved)
    .length;
  const recentlyResolved = withState.filter((a) => {
    if (!a.resolved || !a.state?.resolved_at) return false;
    const days =
      (Date.now() - new Date(a.state.resolved_at).getTime()) / 86_400_000;
    return days <= 7;
  }).length;

  // Contacts for the action row (one round-trip).
  const orgIds = Array.from(new Set(sorted.map((a) => a.orgId)));
  const contacts = orgIds.length
    ? await getOwnerContactsForOrgs(orgIds)
    : new Map<string, OwnerContact>();

  const banner = (() => {
    if (sp.saved === "1") return { tone: "ok" as const, msg: "Alert updated." };
    if (sp.error === "invalid_input")
      return { tone: "err" as const, msg: "Invalid input — please try again." };
    if (sp.error === "update_failed")
      return {
        tone: "err" as const,
        msg: "Update failed. Check logs for details.",
      };
    return null;
  })();

  return (
    <Surface>
      <GlowHeader
        eyebrow="CrewFlow HQ"
        title="Action centre"
        subtitle={
          <>
            Deterministic rules engine across every customer. Critical first.
            Resolved alerts auto-archive — toggle &ldquo;Show resolved&rdquo; to
            bring them back.
          </>
        }
        actions={
          <ButtonLink href="/admin/overview" variant="glass" size="sm">
            ← HQ overview
          </ButtonLink>
        }
      />

      <div className="space-y-6 p-5 sm:p-7">
        {banner ? (
          <AlertBanner tone={banner.tone === "ok" ? "success" : "danger"}>
            {banner.msg}
          </AlertBanner>
        ) : null}

        {/* AI COO PANEL ------------------------------------------------- */}
        <CooPanel alerts={actionCentre} />

        {/* KPI tiles --------------------------------------------------- */}
        <section className="grid grid-cols-2 gap-3 md:grid-cols-4">
          <StatTile
            label="Open critical"
            value={<AnimatedNumber value={openCritical} />}
            accent={openCritical > 0 ? "rose" : "slate"}
          />
          <StatTile
            label="Open warning"
            value={<AnimatedNumber value={openWarning} />}
            accent={openWarning > 0 ? "amber" : "slate"}
          />
          <StatTile
            label="Unread"
            value={<AnimatedNumber value={unread} />}
            accent={unread > 0 ? "indigo" : "slate"}
          />
          <StatTile
            label="Resolved this week"
            value={<AnimatedNumber value={recentlyResolved} />}
            accent="emerald"
          />
        </section>

        {/* Filter bar -------------------------------------------------- */}
        <form
          method="get"
          action="/admin/alerts"
          className="flex flex-wrap items-end gap-2 rounded-2xl border border-slate-800 bg-slate-900/40 p-3"
        >
          <label className="flex flex-col text-[11px] font-medium text-slate-400">
            Search customer / reason
            <Input
              type="text"
              name="q"
              defaultValue={q}
              placeholder="e.g. Adams Roofing or migration"
              className="mt-1 w-64"
            />
          </label>
          <label className="flex flex-col text-[11px] font-medium text-slate-400">
            Severity
            <Select name="severity" defaultValue={severity} className="mt-1">
              <option value="all">All</option>
              {ALERT_SEVERITIES.map((s) => (
                <option key={s} value={s}>
                  {SEVERITY_LABEL[s]}
                </option>
              ))}
            </Select>
          </label>
          <label className="flex flex-col text-[11px] font-medium text-slate-400">
            Sort by
            <Select name="sort" defaultValue={sort} className="mt-1">
              {ALERT_SORTS.map((s) => (
                <option key={s} value={s}>
                  {ALERT_SORT_LABELS[s]}
                </option>
              ))}
            </Select>
          </label>
          <label className="flex items-center gap-2 text-[11px] font-medium text-slate-400">
            <input
              type="checkbox"
              name="show"
              value="resolved"
              defaultChecked={showResolved}
              className="h-4 w-4 rounded border-slate-700 bg-slate-900/80 text-indigo-500 focus:ring-indigo-500/30"
            />
            Show resolved + snoozed
          </label>
          <Button type="submit" variant="accent" size="sm">
            Apply
          </Button>
          <ButtonLink href="/admin/alerts" variant="glass" size="sm">
            Reset
          </ButtonLink>
        </form>

        {/* Alert list -------------------------------------------------- */}
        {sorted.length === 0 ? (
          <EmptyState
            title="No alerts match these filters."
            description={
              !showResolved
                ? "Resolved alerts are hidden — toggle 'Show resolved' to bring them back."
                : undefined
            }
          />
        ) : (
          <ul className="space-y-3">
            {sorted.map((a) => (
              <AlertCard key={a.key} alert={a} contact={contacts.get(a.orgId)} />
            ))}
          </ul>
        )}

        <FooterMeta count={sorted.length} totalRules={withState.length} />
      </div>
    </Surface>
  );
}

// =====================================================================
// AI COO panel — "Today needs attention"
// =====================================================================

function CooPanel({ alerts }: { alerts: ReadonlyArray<AlertWithState> }) {
  return (
    <section className="rounded-2xl border border-indigo-500/30 bg-indigo-500/10 p-5">
      <div className="flex items-baseline justify-between gap-2">
        <div>
          <p className="text-[11px] font-semibold uppercase tracking-wider text-indigo-300">
            AI COO · Today needs attention
          </p>
          <p className="text-xs text-slate-400">
            Top {THRESHOLDS.cooPanelLimit} from the rules engine. Deterministic
            today, LLM rerank lands later — same shape.
          </p>
        </div>
        <Link
          href="/admin/alerts?show=resolved"
          className="text-xs font-medium text-indigo-300 transition-colors hover:text-indigo-200"
        >
          See archive →
        </Link>
      </div>
      {alerts.length === 0 ? (
        <p className="mt-4 rounded-xl border border-dashed border-indigo-500/30 bg-slate-900/60 px-3 py-4 text-center text-sm text-slate-400">
          Nothing on fire. Enjoy your morning.
        </p>
      ) : (
        <ol className="mt-4 grid gap-3 md:grid-cols-3">
          {alerts.map((a, i) => (
            <li
              key={a.key}
              className="rounded-xl border border-slate-800 bg-slate-900/60 p-3"
            >
              <p className="text-[10px] font-semibold uppercase tracking-wide text-slate-500">
                #{i + 1} · {SEVERITY_LABEL[a.severity]}
              </p>
              <p className="mt-1 text-base font-semibold text-white">
                {a.orgName}
              </p>
              <p className="text-xs text-slate-300">
                £{a.mrr.toLocaleString("en-GB")} MRR
                {a.health !== null ? ` · Health ${a.health}` : ""}
              </p>
              <p className="mt-2 text-xs italic text-slate-400">
                {a.suggestion}
              </p>
              <ButtonLink
                href={`/admin/customers/${a.orgId}`}
                variant="accent"
                size="sm"
                className="mt-3"
              >
                Open customer →
              </ButtonLink>
            </li>
          ))}
        </ol>
      )}
    </section>
  );
}

// =====================================================================
// Alert card
// =====================================================================

const PHONE_DIGITS_RE = /[^\d+]/g;

function AlertCard({
  alert,
  contact,
}: {
  alert: AlertWithState;
  contact: OwnerContact | undefined;
}) {
  const phone = (contact?.phone ?? "").replace(PHONE_DIGITS_RE, "");
  const email = contact?.email ?? "";
  const waHref = whatsAppHref(contact?.phone ?? null);

  return (
    <li
      className={`rounded-2xl border bg-slate-900/40 p-4 ${
        alert.resolved
          ? "border-emerald-500/30 opacity-75"
          : alert.snoozed
            ? "border-slate-800 opacity-75"
            : alert.unread
              ? "border-slate-700 ring-1 ring-slate-700/60"
              : "border-slate-800"
      }`}
    >
      <div className="flex flex-wrap items-start justify-between gap-3">
        {/* Left: identity */}
        <div className="min-w-0 flex-1">
          <div className="flex flex-wrap items-center gap-2">
            <Badge accent={SEVERITY_ACCENT[alert.severity]}>
              {SEVERITY_LABEL[alert.severity]}
            </Badge>
            <span className="text-[11px] font-medium text-slate-500">
              {alert.ruleLabel}
            </span>
            {alert.unread ? (
              <Badge accent="indigo">Unread</Badge>
            ) : null}
            {alert.snoozed ? (
              <Badge accent="slate">
                Snoozed until{" "}
                {alert.state?.snoozed_until?.slice(0, 10) ?? "—"}
              </Badge>
            ) : null}
            {alert.resolved ? (
              <Badge accent="emerald">
                Resolved {alert.state?.resolved_at?.slice(0, 10) ?? "—"}
              </Badge>
            ) : null}
          </div>
          <h2 className="mt-1 text-base font-bold text-white">
            {alert.orgName}
          </h2>
          <div className="mt-1 grid grid-cols-2 gap-x-4 gap-y-1 text-xs text-slate-300 sm:grid-cols-3">
            <Field
              label="MRR"
              value={`£${alert.mrr.toLocaleString("en-GB")}`}
            />
            <Field
              label="Health"
              value={alert.health !== null ? `${alert.health}/100` : "—"}
            />
            <Field label="Risk" value={alert.healthRisk ?? "—"} />
          </div>
          <div className="mt-3">
            <p className="text-[11px] font-semibold uppercase tracking-wide text-slate-500">
              Reason
            </p>
            <ul className="mt-1 list-disc pl-5 text-sm text-slate-300">
              {alert.reason.map((r, idx) => (
                <li key={idx}>{r}</li>
              ))}
            </ul>
          </div>
          <p className="mt-3 text-sm">
            <span className="text-[11px] font-semibold uppercase tracking-wide text-slate-500">
              Suggested action
            </span>
            <br />
            <span className="font-medium text-white">
              {alert.suggestion}
            </span>
          </p>
        </div>

        {/* Right: contact + lifecycle actions */}
        <div className="flex w-full flex-col gap-3 sm:w-auto">
          <div className="flex flex-wrap items-center gap-2">
            {phone ? (
              <ButtonLink href={`tel:${phone}`} external variant="glass" size="sm">
                Call
              </ButtonLink>
            ) : null}
            {email ? (
              <ButtonLink
                href={`mailto:${email}`}
                external
                variant="glass"
                size="sm"
              >
                Email
              </ButtonLink>
            ) : null}
            {waHref ? (
              <ButtonLink
                href={waHref}
                external
                target="_blank"
                rel="noreferrer noopener"
                size="sm"
                className="border border-emerald-400/30 bg-emerald-500/15 text-emerald-300 shadow-none transition-colors hover:bg-emerald-500/25 focus-visible:ring-emerald-500 focus-visible:ring-offset-slate-950"
              >
                WhatsApp
              </ButtonLink>
            ) : null}
            <ButtonLink
              href={`/admin/customers/${alert.orgId}`}
              variant="glass"
              size="sm"
            >
              Open customer
            </ButtonLink>
          </div>
          <div className="flex flex-wrap items-center gap-2">
            {alert.resolved ? (
              <ClientConfirmForm
                action={reopenAlert}
                confirm={`Reopen "${alert.ruleLabel}" for ${alert.orgName}? It will reappear in the active queue.`}
              >
                <input type="hidden" name="rule_id" value={alert.ruleId} />
                <input type="hidden" name="org_id" value={alert.orgId} />
                <Button type="submit" variant="glass" size="sm">
                  Reopen
                </Button>
              </ClientConfirmForm>
            ) : (
              <>
                <ResolveForm ruleId={alert.ruleId} orgId={alert.orgId} />
                <SnoozeForm ruleId={alert.ruleId} orgId={alert.orgId} />
                {alert.unread ? (
                  <form action={markAlertRead}>
                    <input type="hidden" name="rule_id" value={alert.ruleId} />
                    <input type="hidden" name="org_id" value={alert.orgId} />
                    <Button type="submit" variant="glass" size="sm">
                      Mark read
                    </Button>
                  </form>
                ) : null}
              </>
            )}
          </div>
        </div>
      </div>
    </li>
  );
}

function ResolveForm({ ruleId, orgId }: { ruleId: string; orgId: string }) {
  return (
    <ClientConfirmForm
      action={markAlertResolved}
      confirm="Mark this alert resolved? The notification dedup is cleared so a future re-fire will ping HQ again."
      className="flex items-center gap-1"
    >
      <input type="hidden" name="rule_id" value={ruleId} />
      <input type="hidden" name="org_id" value={orgId} />
      <Input
        type="text"
        name="resolution_note"
        placeholder="Note (optional)"
        maxLength={2000}
        className="w-40 px-2 py-1.5 text-xs"
      />
      <Button
        type="submit"
        size="sm"
        className="border border-emerald-400/30 bg-emerald-500/15 text-emerald-300 shadow-none transition-colors hover:bg-emerald-500/25 focus-visible:ring-emerald-500 focus-visible:ring-offset-slate-950"
      >
        Mark resolved
      </Button>
    </ClientConfirmForm>
  );
}

function SnoozeForm({ ruleId, orgId }: { ruleId: string; orgId: string }) {
  return (
    <ClientConfirmForm
      action={snoozeAlert}
      confirm="Snooze this alert? It will be hidden from the active queue until the snooze window ends."
      className="flex items-center gap-1"
    >
      <input type="hidden" name="rule_id" value={ruleId} />
      <input type="hidden" name="org_id" value={orgId} />
      <Select name="preset" defaultValue="3d" className="px-2 py-1.5 text-xs">
        <option value="1d">1 day</option>
        <option value="3d">3 days</option>
        <option value="7d">7 days</option>
        <option value="30d">30 days</option>
      </Select>
      <Button type="submit" variant="glass" size="sm">
        Snooze
      </Button>
    </ClientConfirmForm>
  );
}

// =====================================================================
// Bits
// =====================================================================

function Field({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <p className="text-[10px] font-semibold uppercase tracking-wide text-slate-500">
        {label}
      </p>
      <p className="text-sm font-medium text-white">{value}</p>
    </div>
  );
}

function FooterMeta({
  count,
  totalRules,
}: {
  count: number;
  totalRules: number;
}) {
  return (
    <footer className="border-t border-slate-800 pt-3 text-[11px] text-slate-500">
      Showing {count} of {totalRules} alerts. Engine is deterministic — re-runs
      on every page load. LLM rerank lands later without changing this surface.
    </footer>
  );
}

// Mark this page dynamic — the rules engine reads live data and the
// snapshot includes time-relative computations (days since N).
export const dynamic = "force-dynamic";

// Keep a re-export so deep-imported types stay reachable for future
// channel dispatchers that consume Alert directly.
export type _AlertSurface = Alert;
