import Link from "next/link";
import {
  buildAlertsSnapshot,
  getOwnerContactsForOrgs,
  type OwnerContact,
} from "@/server/services/hq-alerts-snapshot";
import {
  runAlertRules,
  sortAlerts,
  filterAlerts,
  applyStateToAlerts,
  pickActionCentre,
  ALERT_SEVERITIES,
  ALERT_SORTS,
  ALERT_SORT_LABELS,
  SEVERITY_LABEL,
  SEVERITY_PILL,
  THRESHOLDS,
  type Alert,
  type AlertSeverity,
  type AlertSort,
  type AlertWithState,
} from "@/lib/hq/alert-rules";
import {
  markAlertRead,
  markAlertResolved,
  snoozeAlert,
  reopenAlert,
} from "./actions";
import { ClientConfirmForm } from "../_client-confirm";

/**
 * Alerts + AI COO — HQ-5.
 *
 * Single place that surfaces every customer who needs attention,
 * generated by a deterministic rules engine (lib/hq/alert-rules.ts).
 * No LLM — pure rule firings against the existing data.
 *
 * Layout:
 *   1. AI COO panel at the top — "Today needs attention" — picks
 *      the top 3 critical/warning alerts deduped by org.
 *   2. KPI tiles — open critical / open warning / unread / resolved 7d.
 *   3. Filter bar — severity / search / sort / show resolved.
 *   4. List of alerts. Each card carries the directive's full
 *      action set: Call · Email · WhatsApp · Open customer ·
 *      Mark resolved · Snooze · Mark read.
 *
 * Auto-archive: resolved alerts disappear from the default view.
 * The list filters where resolved_at IS NULL unless ?show=resolved.
 *
 * Future-compat: LLM rerankers swap in at pickActionCentre without
 * changing the surrounding page. Channel dispatchers (email /
 * WhatsApp / SMS) iterate the same alert list — no schema work.
 */

type SP = Promise<{
  q?: string;
  severity?: string;
  sort?: string;
  show?: string;
  saved?: string;
  error?: string;
}>;

export default async function HqAlertsPage({
  searchParams,
}: {
  searchParams: SP;
}) {
  const sp = await searchParams;
  const q = (sp.q ?? "").trim();
  const severity = (sp.severity ?? "all") as AlertSeverity | "all";
  const sort = (ALERT_SORTS.includes(sp.sort as AlertSort)
    ? sp.sort
    : "severity") as AlertSort;
  const showResolved = sp.show === "resolved";

  const { snapshot, states } = await buildAlertsSnapshot();
  const baseAlerts = runAlertRules(snapshot);
  const withState = applyStateToAlerts(baseAlerts, states, snapshot.now);

  // Visible set: drop snoozed + resolved unless ?show=resolved.
  const visible = withState.filter((a) => {
    if (a.snoozed) return showResolved;
    if (a.resolved) return showResolved;
    return true;
  });

  const filtered = filterAlerts(visible, { severity, q });
  const sorted = sortAlerts(filtered, sort);

  // AI COO panel — operates on the full visible set, not the
  // filtered one (so the picker doesn't disappear when you search).
  const actionCentre = pickActionCentre(visible);

  // KPIs computed against the full alert set (not the visible
  // filter) so the operator sees system-wide truth.
  const openCritical = withState.filter(
    (a) => a.severity === "critical" && !a.resolved && !a.snoozed,
  ).length;
  const openWarning = withState.filter(
    (a) => a.severity === "warning" && !a.resolved && !a.snoozed,
  ).length;
  const unread = withState.filter((a) => a.unread && !a.snoozed && !a.resolved)
    .length;
  const recentlyResolved = withState.filter((a) => {
    if (!a.resolved || !a.state?.resolved_at) return false;
    const days =
      (Date.now() - new Date(a.state.resolved_at).getTime()) / 86_400_000;
    return days <= 7;
  }).length;

  // Contacts for the action row (one round-trip).
  const orgIds = Array.from(new Set(sorted.map((a) => a.orgId)));
  const contacts = orgIds.length
    ? await getOwnerContactsForOrgs(orgIds)
    : new Map<string, OwnerContact>();

  const banner = (() => {
    if (sp.saved === "1") return { tone: "ok" as const, msg: "Alert updated." };
    if (sp.error === "invalid_input")
      return { tone: "err" as const, msg: "Invalid input — please try again." };
    if (sp.error === "update_failed")
      return {
        tone: "err" as const,
        msg: "Update failed. Check logs for details.",
      };
    return null;
  })();

  return (
    <div className="space-y-6 p-6">
      <header className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <p className="text-[11px] font-semibold uppercase tracking-wider text-slate-500">
            HQ · Alerts
          </p>
          <h1 className="text-2xl font-bold text-slate-900">Action centre</h1>
          <p className="mt-1 max-w-2xl text-sm text-slate-600">
            Deterministic rules engine across every customer. Critical first.
            Resolved alerts auto-archive — toggle &ldquo;Show resolved&rdquo; to bring them back.
          </p>
        </div>
        <div className="flex items-center gap-2">
          <Link
            href="/admin/overview"
            className="rounded-md border border-slate-300 bg-white px-3 py-1.5 text-xs font-medium text-slate-700 hover:bg-slate-50"
          >
            ← HQ overview
          </Link>
        </div>
      </header>

      {banner ? (
        <div
          className={`rounded-md border px-3 py-2 text-sm ${
            banner.tone === "ok"
              ? "border-emerald-200 bg-emerald-50 text-emerald-900"
              : "border-red-200 bg-red-50 text-red-800"
          }`}
        >
          {banner.msg}
        </div>
      ) : null}

      {/* AI COO PANEL ------------------------------------------------- */}
      <CooPanel alerts={actionCentre} />

      {/* KPI tiles --------------------------------------------------- */}
      <section className="grid grid-cols-2 gap-3 md:grid-cols-4">
        <Kpi label="Open critical" value={String(openCritical)} tone="red" />
        <Kpi label="Open warning" value={String(openWarning)} tone="amber" />
        <Kpi label="Unread" value={String(unread)} tone="blue" />
        <Kpi
          label="Resolved this week"
          value={String(recentlyResolved)}
          tone="emerald"
        />
      </section>

      {/* Filter bar -------------------------------------------------- */}
      <form
        method="get"
        action="/admin/alerts"
        className="flex flex-wrap items-end gap-2 rounded-lg border border-slate-200 bg-white p-3 shadow-sm"
      >
        <label className="flex flex-col text-[11px] font-medium text-slate-700">
          Search customer / reason
          <input
            type="text"
            name="q"
            defaultValue={q}
            placeholder="e.g. Adams Roofing or migration"
            className="mt-1 w-64 rounded-md border border-slate-300 px-3 py-1.5 text-sm shadow-sm focus:border-slate-500 focus:outline-none focus:ring-1 focus:ring-slate-500"
          />
        </label>
        <label className="flex flex-col text-[11px] font-medium text-slate-700">
          Severity
          <select
            name="severity"
            defaultValue={severity}
            className="mt-1 rounded-md border border-slate-300 px-2 py-1.5 text-sm"
          >
            <option value="all">All</option>
            {ALERT_SEVERITIES.map((s) => (
              <option key={s} value={s}>
                {SEVERITY_LABEL[s]}
              </option>
            ))}
          </select>
        </label>
        <label className="flex flex-col text-[11px] font-medium text-slate-700">
          Sort by
          <select
            name="sort"
            defaultValue={sort}
            className="mt-1 rounded-md border border-slate-300 px-2 py-1.5 text-sm"
          >
            {ALERT_SORTS.map((s) => (
              <option key={s} value={s}>
                {ALERT_SORT_LABELS[s]}
              </option>
            ))}
          </select>
        </label>
        <label className="flex items-center gap-2 text-[11px] font-medium text-slate-700">
          <input
            type="checkbox"
            name="show"
            value="resolved"
            defaultChecked={showResolved}
          />
          Show resolved + snoozed
        </label>
        <button
          type="submit"
          className="rounded-md bg-slate-900 px-3 py-1.5 text-xs font-semibold text-white hover:bg-slate-700"
        >
          Apply
        </button>
        <Link
          href="/admin/alerts"
          className="rounded-md border border-slate-300 bg-white px-3 py-1.5 text-xs font-medium text-slate-700 hover:bg-slate-50"
        >
          Reset
        </Link>
      </form>

      {/* Alert list -------------------------------------------------- */}
      {sorted.length === 0 ? (
        <p className="rounded-md border border-dashed border-slate-300 bg-white px-4 py-6 text-center text-sm text-slate-500">
          No alerts match these filters.{" "}
          {!showResolved
            ? "Resolved alerts are hidden — toggle 'Show resolved' to bring them back."
            : ""}
        </p>
      ) : (
        <ul className="space-y-3">
          {sorted.map((a) => (
            <AlertCard key={a.key} alert={a} contact={contacts.get(a.orgId)} />
          ))}
        </ul>
      )}

      <FooterMeta count={sorted.length} totalRules={withState.length} />
    </div>
  );
}

// =====================================================================
// AI COO panel — "Today needs attention"
// =====================================================================

function CooPanel({ alerts }: { alerts: ReadonlyArray<AlertWithState> }) {
  return (
    <section className="rounded-2xl border border-indigo-200 bg-gradient-to-br from-indigo-50 via-white to-white p-5 shadow-sm">
      <div className="flex items-baseline justify-between gap-2">
        <div>
          <p className="text-[11px] font-semibold uppercase tracking-wider text-indigo-700">
            AI COO · Today needs attention
          </p>
          <p className="text-xs text-slate-600">
            Top {THRESHOLDS.cooPanelLimit} from the rules engine. Deterministic
            today, LLM rerank lands later — same shape.
          </p>
        </div>
        <Link
          href="/admin/alerts?show=resolved"
          className="text-xs font-medium text-indigo-700 hover:underline"
        >
          See archive →
        </Link>
      </div>
      {alerts.length === 0 ? (
        <p className="mt-4 rounded-md border border-dashed border-indigo-200 bg-white px-3 py-4 text-center text-sm text-slate-500">
          Nothing on fire. Enjoy your morning.
        </p>
      ) : (
        <ol className="mt-4 grid gap-3 md:grid-cols-3">
          {alerts.map((a, i) => (
            <li
              key={a.key}
              className="rounded-lg border border-slate-200 bg-white p-3 shadow-sm"
            >
              <p className="text-[10px] font-semibold uppercase tracking-wide text-slate-500">
                #{i + 1} · {SEVERITY_LABEL[a.severity]}
              </p>
              <p className="mt-1 text-base font-semibold text-slate-900">
                {a.orgName}
              </p>
              <p className="text-xs text-slate-700">
                £{a.mrr.toLocaleString("en-GB")} MRR
                {a.health !== null ? ` · Health ${a.health}` : ""}
              </p>
              <p className="mt-2 text-xs italic text-slate-600">
                {a.suggestion}
              </p>
              <Link
                href={`/admin/customers/${a.orgId}`}
                className="mt-3 inline-block rounded-md bg-indigo-700 px-3 py-1.5 text-xs font-semibold text-white hover:bg-indigo-800"
              >
                Open customer →
              </Link>
            </li>
          ))}
        </ol>
      )}
    </section>
  );
}

// =====================================================================
// Alert card
// =====================================================================

const PHONE_DIGITS_RE = /[^\d+]/g;

function AlertCard({
  alert,
  contact,
}: {
  alert: AlertWithState;
  contact: OwnerContact | undefined;
}) {
  const phone = (contact?.phone ?? "").replace(PHONE_DIGITS_RE, "");
  const email = contact?.email ?? "";

  return (
    <li
      className={`rounded-xl border bg-white p-4 shadow-sm ${
        alert.resolved
          ? "border-emerald-200 opacity-75"
          : alert.snoozed
            ? "border-slate-200 opacity-75"
            : alert.unread
              ? "border-slate-300 ring-1 ring-slate-200"
              : "border-slate-200"
      }`}
    >
      <div className="flex flex-wrap items-start justify-between gap-3">
        {/* Left: identity */}
        <div className="min-w-0 flex-1">
          <div className="flex flex-wrap items-center gap-2">
            <span
              className={`inline-flex items-center rounded-full border px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide ${SEVERITY_PILL[alert.severity]}`}
            >
              {SEVERITY_LABEL[alert.severity]}
            </span>
            <span className="text-[11px] font-medium text-slate-500">
              {alert.ruleLabel}
            </span>
            {alert.unread ? (
              <span className="rounded-full bg-blue-100 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-blue-900">
                Unread
              </span>
            ) : null}
            {alert.snoozed ? (
              <span className="rounded-full bg-slate-200 px-2 py-0.5 text-[10px] font-medium text-slate-700">
                Snoozed until{" "}
                {alert.state?.snoozed_until?.slice(0, 10) ?? "—"}
              </span>
            ) : null}
            {alert.resolved ? (
              <span className="rounded-full bg-emerald-100 px-2 py-0.5 text-[10px] font-medium text-emerald-900">
                Resolved {alert.state?.resolved_at?.slice(0, 10) ?? "—"}
              </span>
            ) : null}
          </div>
          <h2 className="mt-1 text-base font-bold text-slate-900">
            {alert.orgName}
          </h2>
          <div className="mt-1 grid grid-cols-2 gap-x-4 gap-y-1 text-xs text-slate-700 sm:grid-cols-3">
            <Field
              label="MRR"
              value={`£${alert.mrr.toLocaleString("en-GB")}`}
            />
            <Field
              label="Health"
              value={alert.health !== null ? `${alert.health}/100` : "—"}
            />
            <Field label="Risk" value={alert.healthRisk ?? "—"} />
          </div>
          <div className="mt-3">
            <p className="text-[11px] font-semibold uppercase tracking-wide text-slate-500">
              Reason
            </p>
            <ul className="mt-1 list-disc pl-5 text-sm text-slate-800">
              {alert.reason.map((r, idx) => (
                <li key={idx}>{r}</li>
              ))}
            </ul>
          </div>
          <p className="mt-3 text-sm">
            <span className="text-[11px] font-semibold uppercase tracking-wide text-slate-500">
              Suggested action
            </span>
            <br />
            <span className="font-medium text-slate-900">
              {alert.suggestion}
            </span>
          </p>
        </div>

        {/* Right: contact + lifecycle actions */}
        <div className="flex w-full flex-col gap-3 sm:w-auto">
          <div className="flex flex-wrap items-center gap-2">
            {phone ? (
              <a
                href={`tel:${phone}`}
                className="rounded-md border border-slate-300 bg-white px-3 py-1.5 text-xs font-medium text-slate-700 hover:bg-slate-50"
              >
                Call
              </a>
            ) : null}
            {email ? (
              <a
                href={`mailto:${email}`}
                className="rounded-md border border-slate-300 bg-white px-3 py-1.5 text-xs font-medium text-slate-700 hover:bg-slate-50"
              >
                Email
              </a>
            ) : null}
            {phone ? (
              <a
                href={`https://wa.me/${phone.replace(/[^\d]/g, "")}`}
                target="_blank"
                rel="noreferrer noopener"
                className="rounded-md border border-emerald-300 bg-emerald-50 px-3 py-1.5 text-xs font-medium text-emerald-900 hover:bg-emerald-100"
              >
                WhatsApp
              </a>
            ) : null}
            <Link
              href={`/admin/customers/${alert.orgId}`}
              className="rounded-md border border-indigo-300 bg-indigo-50 px-3 py-1.5 text-xs font-medium text-indigo-900 hover:bg-indigo-100"
            >
              Open customer
            </Link>
          </div>
          <div className="flex flex-wrap items-center gap-2">
            {alert.resolved ? (
              <ClientConfirmForm
                action={reopenAlert}
                confirm={`Reopen "${alert.ruleLabel}" for ${alert.orgName}? It will reappear in the active queue.`}
              >
                <input type="hidden" name="rule_id" value={alert.ruleId} />
                <input type="hidden" name="org_id" value={alert.orgId} />
                <button
                  type="submit"
                  className="rounded-md border border-slate-300 bg-white px-3 py-1.5 text-xs font-medium text-slate-700 hover:bg-slate-50"
                >
                  Reopen
                </button>
              </ClientConfirmForm>
            ) : (
              <>
                <ResolveForm ruleId={alert.ruleId} orgId={alert.orgId} />
                <SnoozeForm ruleId={alert.ruleId} orgId={alert.orgId} />
                {alert.unread ? (
                  <form action={markAlertRead}>
                    <input type="hidden" name="rule_id" value={alert.ruleId} />
                    <input type="hidden" name="org_id" value={alert.orgId} />
                    <button
                      type="submit"
                      className="rounded-md border border-slate-300 bg-white px-3 py-1.5 text-xs font-medium text-slate-700 hover:bg-slate-50"
                    >
                      Mark read
                    </button>
                  </form>
                ) : null}
              </>
            )}
          </div>
        </div>
      </div>
    </li>
  );
}

function ResolveForm({ ruleId, orgId }: { ruleId: string; orgId: string }) {
  return (
    <ClientConfirmForm
      action={markAlertResolved}
      confirm="Mark this alert resolved? The notification dedup is cleared so a future re-fire will ping HQ again."
      className="flex items-center gap-1"
    >
      <input type="hidden" name="rule_id" value={ruleId} />
      <input type="hidden" name="org_id" value={orgId} />
      <input
        type="text"
        name="resolution_note"
        placeholder="Note (optional)"
        maxLength={2000}
        className="w-40 rounded-md border border-slate-300 px-2 py-1 text-xs shadow-sm focus:border-slate-500 focus:outline-none focus:ring-1 focus:ring-slate-500"
      />
      <button
        type="submit"
        className="rounded-md bg-emerald-700 px-3 py-1.5 text-xs font-semibold text-white hover:bg-emerald-800"
      >
        Mark resolved
      </button>
    </ClientConfirmForm>
  );
}

function SnoozeForm({ ruleId, orgId }: { ruleId: string; orgId: string }) {
  return (
    <ClientConfirmForm
      action={snoozeAlert}
      confirm="Snooze this alert? It will be hidden from the active queue until the snooze window ends."
      className="flex items-center gap-1"
    >
      <input type="hidden" name="rule_id" value={ruleId} />
      <input type="hidden" name="org_id" value={orgId} />
      <select
        name="preset"
        defaultValue="3d"
        className="rounded-md border border-slate-300 px-2 py-1 text-xs"
      >
        <option value="1d">1 day</option>
        <option value="3d">3 days</option>
        <option value="7d">7 days</option>
        <option value="30d">30 days</option>
      </select>
      <button
        type="submit"
        className="rounded-md border border-slate-300 bg-white px-3 py-1.5 text-xs font-medium text-slate-700 hover:bg-slate-50"
      >
        Snooze
      </button>
    </ClientConfirmForm>
  );
}

// =====================================================================
// Bits
// =====================================================================

function Kpi({
  label,
  value,
  tone,
}: {
  label: string;
  value: string;
  tone: "red" | "amber" | "blue" | "emerald";
}) {
  const colourise: Record<typeof tone, string> = {
    red: "bg-red-50 border-red-200 text-red-900",
    amber: "bg-amber-50 border-amber-200 text-amber-900",
    blue: "bg-blue-50 border-blue-200 text-blue-900",
    emerald: "bg-emerald-50 border-emerald-200 text-emerald-900",
  };
  return (
    <div className={`rounded-xl border p-3 shadow-sm ${colourise[tone]}`}>
      <p className="text-[10px] font-semibold uppercase tracking-wide opacity-75">
        {label}
      </p>
      <p className="mt-1 text-2xl font-bold">{value}</p>
    </div>
  );
}

function Field({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <p className="text-[10px] font-semibold uppercase tracking-wide text-slate-500">
        {label}
      </p>
      <p className="text-sm font-medium text-slate-900">{value}</p>
    </div>
  );
}

function FooterMeta({
  count,
  totalRules,
}: {
  count: number;
  totalRules: number;
}) {
  return (
    <footer className="border-t border-slate-200 pt-3 text-[11px] text-slate-500">
      Showing {count} of {totalRules} alerts. Engine is deterministic — re-runs
      on every page load. LLM rerank lands later without changing this surface.
    </footer>
  );
}

// Mark this page dynamic — the rules engine reads live data and the
// snapshot includes time-relative computations (days since N).
export const dynamic = "force-dynamic";

// Keep a re-export so deep-imported types stay reachable for future
// channel dispatchers that consume Alert directly.
export type _AlertSurface = Alert;
