-- Asset Management — Milestone 4d: permissioned safety overrides, explicit
-- reinspection lineage, the supersede-escape hardening, and pre-use enforcement.
--
-- ONE custody-guard replacement carries every M4d arm (the guard is the
-- highest-risk shared object; it changes once). Four concerns:
--
--   1. OVERRIDES. An admin can record a formal, audited, per-fail operational
--      override — it bypasses EXACTLY ONE blocking fail, never "the asset",
--      never silently: mandatory reason, member-visible, optional expiry that
--      re-blocks purely by time predicate (no cron), write-once revocation.
--      An override NEVER alters the inspection it bypasses.
--   2. EXPLICIT REINSPECTION LINEAGE. `reinspection_of` links a clearing pass
--      to the exact fail it clears — timestamp-independent (a legitimately
--      backdated pass still clears ITS fail), scoped to exactly one fail. The
--      M4c later-pass rule remains as the documented fallback, so existing
--      behaviour and its test suite stay green.
--   3. SUPERSEDE-ESCAPE HARDENING (threat A4.9). Previously a member could
--      UPDATE a blocking fail to status='superseded' (the immutability trigger
--      deliberately leaves status transitions open), dropping it out of the
--      guard's `f.status='issued'` universe with no pass, no override, no
--      admin. Now a safety-critical FAIL can only leave 'issued' when an
--      ISSUED successor exists (a revision or a linked re-inspection).
--   4. PRE-USE ENFORCEMENT (M4b-2's required_for_assignment seam). A new open
--      assignment is refused while the asset has a DUE, UNCOMPLETED draft
--      inspection generated by an ACTIVE schedule marked required-for-
--      assignment — "complete the required pre-use check before issuing".
--      Pure row-state predicate: completing the check (draft → issued)
--      unblocks; pausing the schedule or unticking the flag (admin) is the
--      escape valve. No clock-window logic.
--
-- The three-arm clearing test lives in ONE shared function
-- (asset_inspection_fail_is_cleared) so the custody guard and M5's
-- return-to-service gate can never drift.

-- ── 1. The overrides table ────────────────────────────────────────────────────
create table if not exists public.asset_inspection_overrides (
  id            uuid primary key default gen_random_uuid(),
  org_id        uuid not null references public.organizations(id) on delete cascade,
  asset_id      uuid not null references public.assets(id) on delete cascade,
  -- THE POINT: an override bypasses EXACTLY ONE blocking fail.
  inspection_id uuid not null references public.asset_inspections(id) on delete cascade,
  reason        text not null,
  expires_at    timestamp with time zone,       -- nullable; the UI recommends one
  created_by    uuid references public.users(id) on delete set null,
  created_at    timestamp with time zone not null default now(),
  revoked_at    timestamp with time zone,
  revoked_by    uuid references public.users(id) on delete set null,
  revoke_reason text,
  updated_at    timestamp with time zone not null default now(),
  constraint asset_inspection_overrides_reason_check
    check (length(btrim(reason)) >= 10),        -- mandatory, non-trivial reason
  constraint asset_inspection_overrides_expiry_check
    check (expires_at is null or expires_at > created_at),
  -- One-directional pairing only: revoked_by/revoke_reason imply revoked_at.
  -- (Bidirectional equality would make `on delete set null` on revoked_by fail
  -- user deletion.)
  constraint asset_inspection_overrides_revoked_by_check
    check (revoked_by is null or revoked_at is not null),
  constraint asset_inspection_overrides_revoke_reason_check
    check (revoke_reason is null or revoked_at is not null)
);

-- THE INVARIANT + the guard's probe: at most one LIVE (un-revoked) override per
-- fail — two concurrent creates get exactly one 23505 loser; re-overriding
-- after expiry forces an explicit revoke first (two audit events, no silent
-- extension).
create unique index if not exists asset_inspection_overrides_one_live_idx
  on public.asset_inspection_overrides (inspection_id) where revoked_at is null;

create index if not exists asset_inspection_overrides_asset_idx
  on public.asset_inspection_overrides (asset_id, created_at desc);
create index if not exists asset_inspection_overrides_org_idx
  on public.asset_inspection_overrides (org_id, created_at desc);

-- ── 2. RLS ────────────────────────────────────────────────────────────────────
alter table public.asset_inspection_overrides enable row level security;

-- MEMBER-VISIBLE SELECT is required for CORRECTNESS, not courtesy: the custody
-- guard runs SECURITY INVOKER under the issuing member's RLS — if members could
-- not read overrides, the bypass would never engage for them. It is also the
-- abuse deterrent (overrides are never secret).
create policy asset_inspection_overrides_select on public.asset_inspection_overrides
  for select using (org_id in (select public.current_org_ids()));
-- Create/revoke are ADMIN-ONLY at RLS (and checked again in the action).
create policy asset_inspection_overrides_insert on public.asset_inspection_overrides
  for insert with check (public.is_org_admin(org_id));
create policy asset_inspection_overrides_update on public.asset_inspection_overrides
  for update using (public.is_org_admin(org_id))
  with check (public.is_org_admin(org_id));
create policy asset_inspection_overrides_delete on public.asset_inspection_overrides
  for delete using (public.is_org_admin(org_id));

-- ── 3. Override guard: audit-record immutability + target validation ─────────
create or replace function public.tg_asset_inspection_overrides_guard()
returns trigger language plpgsql as $$
declare
  i_org uuid;
  i_asset uuid;
  i_safety boolean;
  i_status text;
  i_outcome text;
begin
  if tg_op = 'UPDATE' then
    -- An override is an audit record: ONLY revocation may ever change, once.
    if new.org_id <> old.org_id or new.asset_id <> old.asset_id
       or new.inspection_id <> old.inspection_id
       or new.reason is distinct from old.reason
       or new.expires_at is distinct from old.expires_at
       or new.created_by is distinct from old.created_by
       or new.created_at is distinct from old.created_at then
      raise exception 'override % is immutable except revocation', old.id
        using errcode = 'check_violation';
    end if;
    if old.revoked_at is not null
       and (new.revoked_at is distinct from old.revoked_at
            or new.revoked_by is distinct from old.revoked_by
            or new.revoke_reason is distinct from old.revoke_reason) then
      raise exception 'override % is revoked and can no longer change', old.id
        using errcode = 'check_violation';
    end if;
    return new;
  end if;

  -- INSERT: the target must be a same-org, same-asset ISSUED safety-critical
  -- FAIL — exactly the shape the custody guard blocks on.
  select org_id, asset_id, safety_critical, status, outcome
    into i_org, i_asset, i_safety, i_status, i_outcome
    from public.asset_inspections where id = new.inspection_id;
  if i_org is null or i_org <> new.org_id then
    raise exception 'inspection % is not in org %', new.inspection_id, new.org_id
      using errcode = 'check_violation';
  end if;
  if i_asset <> new.asset_id then
    raise exception 'inspection % is not for asset %', new.inspection_id, new.asset_id
      using errcode = 'check_violation';
  end if;
  if not (i_safety and i_status = 'issued' and i_outcome = 'fail') then
    raise exception 'override target % is not an issued safety-critical fail', new.inspection_id
      using errcode = 'check_violation';
  end if;
  return new;
end $$;

drop trigger if exists asset_inspection_overrides_guard on public.asset_inspection_overrides;
create trigger asset_inspection_overrides_guard
  before insert or update on public.asset_inspection_overrides
  for each row execute function public.tg_asset_inspection_overrides_guard();

drop trigger if exists asset_inspection_overrides_set_updated_at on public.asset_inspection_overrides;
create trigger asset_inspection_overrides_set_updated_at
  before update on public.asset_inspection_overrides
  for each row execute function public.tg_set_updated_at();

-- ── 4. Explicit reinspection lineage ─────────────────────────────────────────
alter table public.asset_inspections
  add column if not exists reinspection_of uuid
    references public.asset_inspections(id) on delete set null;

alter table public.asset_inspections
  drop constraint if exists asset_inspections_reinspection_self_check;
alter table public.asset_inspections
  add constraint asset_inspections_reinspection_self_check
  check (reinspection_of is null or reinspection_of <> id);

create index if not exists asset_inspections_reinspection_of_idx
  on public.asset_inspections (reinspection_of)
  where reinspection_of is not null;

-- ── 5. tg_asset_inspections_guard: M4a arms VERBATIM + the lineage arm ───────
create or replace function public.tg_asset_inspections_guard()
returns trigger language plpgsql as $$
declare
  a_org uuid;
begin
  select org_id into a_org from public.assets where id = new.asset_id;
  if a_org is null or a_org <> new.org_id then
    raise exception 'asset % is not in org %', new.asset_id, new.org_id
      using errcode = 'check_violation';
  end if;
  if new.supersedes_id is not null
     and not exists (select 1 from public.asset_inspections
                     where id = new.supersedes_id and org_id = new.org_id) then
    raise exception 'superseded inspection % is not in org %', new.supersedes_id, new.org_id
      using errcode = 'check_violation';
  end if;
  -- M4d: a re-inspection must target a same-org, same-asset, non-draft record.
  if new.reinspection_of is not null
     and not exists (select 1 from public.asset_inspections r
                     where r.id = new.reinspection_of
                       and r.org_id = new.org_id
                       and r.asset_id = new.asset_id
                       and r.status <> 'draft') then
    raise exception 'reinspection target % is not an issued inspection of asset % in org %',
      new.reinspection_of, new.asset_id, new.org_id
      using errcode = 'check_violation';
  end if;
  return new;
end $$;

drop trigger if exists asset_inspections_guard on public.asset_inspections;
create trigger asset_inspections_guard before insert or update on public.asset_inspections
  for each row execute function public.tg_asset_inspections_guard();

-- ── 6. tg_asset_inspections_immutable: M4a arms VERBATIM + lineage freeze +
--       the A4.9 supersede-escape hardening ─────────────────────────────────
create or replace function public.tg_asset_inspections_immutable()
returns trigger language plpgsql as $$
begin
  if old.snapshot is not null and new.snapshot is distinct from old.snapshot then
    raise exception 'asset_inspections.snapshot is immutable once set (inspection %)', old.id
      using errcode = 'check_violation';
  end if;

  if new.status = 'issued' then
    if new.outcome is null then
      raise exception 'an issued inspection requires an outcome (inspection %)', old.id
        using errcode = 'check_violation';
    end if;
    if new.snapshot is null then
      raise exception 'an issued inspection requires a snapshot (inspection %)', old.id
        using errcode = 'check_violation';
    end if;
  end if;

  -- M4d hardening (threat A4.9): a blocking safety-critical FAIL cannot slip
  -- out of the custody guard's universe by being retired — it may leave
  -- 'issued' only when an ISSUED successor exists (a revision that replaces it
  -- or a re-inspection linked to it).
  if old.status = 'issued' and new.status in ('superseded', 'archived')
     and old.safety_critical and old.outcome = 'fail'
     and not exists (
       select 1 from public.asset_inspections n
       where (n.supersedes_id = old.id or n.reinspection_of = old.id)
         and n.status = 'issued'
     ) then
    raise exception 'a blocking safety inspection cannot be retired without an issued successor (inspection %)',
      old.id using errcode = 'check_violation';
  end if;

  if old.status in ('issued', 'superseded', 'archived') then
    if new.content is distinct from old.content then
      raise exception 'asset_inspections.content is frozen after issue (inspection %, status %)',
        old.id, old.status using errcode = 'check_violation';
    end if;
    if new.outcome is distinct from old.outcome then
      raise exception 'asset_inspections.outcome is frozen after issue (inspection %, status %)',
        old.id, old.status using errcode = 'check_violation';
    end if;
    if new.safety_critical is distinct from old.safety_critical then
      raise exception 'asset_inspections.safety_critical is frozen after issue (inspection %)',
        old.id using errcode = 'check_violation';
    end if;
    -- M4d: lineage is part of the frozen record.
    if new.reinspection_of is distinct from old.reinspection_of then
      raise exception 'asset_inspections.reinspection_of is frozen after issue (inspection %)',
        old.id using errcode = 'check_violation';
    end if;
  end if;

  return new;
end $$;

drop trigger if exists asset_inspections_immutable on public.asset_inspections;
create trigger asset_inspections_immutable before update on public.asset_inspections
  for each row execute function public.tg_asset_inspections_immutable();

-- ── 7. THE shared clearing predicate ─────────────────────────────────────────
-- SECURITY INVOKER (caller RLS applies — members can read all three tables,
-- which is load-bearing) + STABLE (now() is transaction-stable). Reused by
-- M5's return-to-service gate so the two sites can never drift.
create or replace function public.asset_inspection_fail_is_cleared(p_inspection_id uuid)
returns boolean
language sql stable as $$
  select
    exists (  -- arm 1 (M4d): an issued safety-critical pass EXPLICITLY linked
      select 1
      from public.asset_inspections lp
      join public.asset_inspections f on f.id = p_inspection_id
      where lp.reinspection_of = f.id
        and lp.asset_id = f.asset_id and lp.org_id = f.org_id
        and lp.safety_critical and lp.status = 'issued'
        and lp.outcome in ('pass', 'pass_with_defects')
    )
    or exists (  -- arm 2 (M4c, verbatim semantics): a LATER issued pass
      select 1
      from public.asset_inspections p
      join public.asset_inspections f on f.id = p_inspection_id
      where p.asset_id = f.asset_id and p.org_id = f.org_id
        and p.safety_critical and p.status = 'issued'
        and p.outcome in ('pass', 'pass_with_defects')
        and coalesce(p.inspected_at, p.created_at) > coalesce(f.inspected_at, f.created_at)
    )
    or exists (  -- arm 3 (M4d): an ACTIVE admin override of exactly this fail
      select 1
      from public.asset_inspection_overrides o
      where o.inspection_id = p_inspection_id
        and o.revoked_at is null
        and (o.expires_at is null or o.expires_at > now())
    );
$$;

-- ── 8. THE custody-guard replacement ─────────────────────────────────────────
-- Every prior check reproduced VERBATIM from 20260928 (same-org asset,
-- active-status eligibility, job/vehicle/assignee references). The safety block
-- now delegates clearing to the shared predicate (raise message byte-identical
-- to M4c — the existing suites assert it), and ONE new arm enforces the
-- pre-use rule.
create or replace function public.tg_asset_assignments_guard()
returns trigger language plpgsql as $$
declare
  a_status text;
  a_org uuid;
begin
  select status, org_id into a_status, a_org from public.assets where id = new.asset_id;
  if a_org is null or a_org <> new.org_id then
    raise exception 'asset % is not in org %', new.asset_id, new.org_id
      using errcode = 'check_violation';
  end if;
  -- A new OPEN assignment requires an ACTIVE asset (retired/sold/lost/stolen/
  -- written_off cannot be issued). Closing/cancelling is always allowed.
  if new.status = 'open' and a_status <> 'active' then
    raise exception 'asset % is % and cannot be assigned', new.asset_id, a_status
      using errcode = 'check_violation';
  end if;
  -- SAFETY BLOCK (M4c + M4d): a new OPEN assignment is refused while the asset
  -- has an issued safety-critical FAIL that is not cleared by (1) a linked
  -- issued pass, (2) a later issued pass [M4c fallback], or (3) an ACTIVE
  -- admin override of exactly that fail (un-revoked, un-expired at now() —
  -- expiry re-blocks with no cron). Only issue-time is gated.
  if new.status = 'open' and exists (
    select 1 from public.asset_inspections f
    where f.asset_id = new.asset_id and f.org_id = new.org_id
      and f.safety_critical and f.status = 'issued' and f.outcome = 'fail'
      and not public.asset_inspection_fail_is_cleared(f.id)
  ) then
    raise exception 'asset % has a failed safety inspection and cannot be issued', new.asset_id
      using errcode = 'check_violation';
  end if;
  -- PRE-USE RULE (M4d, the M4b-2 required_for_assignment seam): a due,
  -- uncompleted draft inspection generated by an ACTIVE required schedule
  -- blocks issue — complete the check to unblock; pausing the schedule or
  -- unticking the flag (admin) is the escape valve.
  if new.status = 'open' and exists (
    select 1
    from public.asset_inspections d
    join public.asset_inspection_schedules s on s.id = d.schedule_id
    where d.asset_id = new.asset_id and d.org_id = new.org_id
      and d.status = 'draft' and d.due_at is not null and d.due_at <= now()
      and s.active and s.required_for_assignment
  ) then
    raise exception 'asset % requires a completed inspection before it can be issued', new.asset_id
      using errcode = 'check_violation';
  end if;
  if new.job_id is not null
     and not exists (select 1 from public.jobs where id = new.job_id and org_id = new.org_id) then
    raise exception 'job % is not in org %', new.job_id, new.org_id
      using errcode = 'check_violation';
  end if;
  if new.vehicle_asset_id is not null
     and not exists (select 1 from public.assets where id = new.vehicle_asset_id and org_id = new.org_id) then
    raise exception 'vehicle asset % is not in org %', new.vehicle_asset_id, new.org_id
      using errcode = 'check_violation';
  end if;
  if new.assignee_id is not null
     and not exists (select 1 from public.memberships where user_id = new.assignee_id and org_id = new.org_id) then
    raise exception 'assignee % is not a member of org %', new.assignee_id, new.org_id
      using errcode = 'check_violation';
  end if;
  return new;
end $$;

drop trigger if exists asset_assignments_guard on public.asset_assignments;
create trigger asset_assignments_guard before insert or update on public.asset_assignments
  for each row execute function public.tg_asset_assignments_guard();
