-- CrewFlow HQ — Shared Memory Engine (CEO Directive 002, Phase 2).
--
-- Builds ON TOP of the Phase 1 AI Employee Framework. This is the
-- single source of truth for company knowledge that every AI employee
-- (CEO AI, CTO AI, Sales AI, …) reads from. Not a chatbot history — a
-- permission-aware, fully-audited company knowledge engine.
--
-- READ-FIRST / FRAMEWORK. Humans (HQ super-admins) author memories
-- through gated server actions; AI employees only READ. No model
-- provider, embedding model, or autonomous write is wired here. The
-- `embedding_placeholder` column is reserved architecture only — it is
-- never populated or read in Phase 2 (no pgvector dependency).
--
-- HQ-ONLY: every table below has RLS ENABLED with NO policies, so only
-- the service-role client can see or touch these rows. The customer /
-- staff user-JWT client can never read company memory. This mirrors the
-- Phase 1 ai_employee* tables and public.internal_notes (HQ-9).
--
-- Tables:
--   hq_memory_types          extensible lookup (new types = a data row, no code)
--   hq_memory_sources        extensible lookup of provenance channels
--   hq_memories              the memory record — single source of truth
--   hq_memory_relationships  polymorphic links to features/PRs/customers/…
--   hq_memory_employee_links memory <-> ai_employee (pinned / relevant / owner)
--   hq_memory_access_grants  explicit grants backing 'restricted' visibility
--   hq_memory_events         per-memory timeline (created/updated/viewed/ai_access)
--   hq_memory_versions       immutable version-history snapshots

-- ---------------------------------------------------------------------
-- Extensible lookups (memory types + sources). FK targets so new types
-- and sources can be added as DATA with no code change, per directive.
-- ---------------------------------------------------------------------

create table if not exists public.hq_memory_types (
  slug                text primary key check (slug ~ '^[a-z0-9_]{1,60}$'),
  label               text not null check (char_length(label) between 1 and 80),
  description         text not null default '' check (char_length(description) <= 600),
  icon                text not null default 'brain',
  accent              text not null default 'slate',
  -- Optional default department a memory of this type lands in.
  default_department  text,
  sort_order          integer not null default 100,
  is_active           boolean not null default true,
  created_at          timestamp with time zone not null default now()
);

alter table public.hq_memory_types enable row level security;
-- NO policies → service-role only.

create table if not exists public.hq_memory_sources (
  slug        text primary key check (slug ~ '^[a-z0-9_]{1,60}$'),
  label       text not null check (char_length(label) between 1 and 80),
  -- 'manual'      authored by a human in the HQ UI
  -- 'system'      generated by CrewFlow itself (deploys, decisions, …)
  -- 'integration' future external connectors (GitHub, Slack, Twilio, …)
  category    text not null default 'manual'
              check (category in ('manual', 'system', 'integration')),
  is_active   boolean not null default true,
  sort_order  integer not null default 100,
  created_at  timestamp with time zone not null default now()
);

alter table public.hq_memory_sources enable row level security;
-- NO policies → service-role only.

-- ---------------------------------------------------------------------
-- The memory record — single source of truth.
--
-- `related_entities` from the directive is modelled relationally via
-- public.hq_memory_relationships (assembled at the service layer) so the
-- graph stays normalised and queryable rather than duplicated as blob.
-- ---------------------------------------------------------------------

create table if not exists public.hq_memories (
  id                uuid primary key default gen_random_uuid(),

  title             text not null check (char_length(title) between 1 and 300),
  summary           text not null default '' check (char_length(summary) <= 2000),
  body              text not null default '' check (char_length(body) <= 200000),

  -- Extensible type. FK to the lookup → adding a type is a data change.
  memory_type       text not null references public.hq_memory_types(slug),

  department        text check (department is null or department in (
                      'executive', 'engineering', 'sales', 'marketing',
                      'design', 'quality', 'documentation', 'product',
                      'finance', 'support', 'operations'
                    )),

  importance        text not null default 'normal'
                    check (importance in ('low', 'normal', 'high', 'critical')),

  tags              text[] not null default '{}',
  -- Auto-derived at the service layer for topic grouping / display.
  keywords          text[] not null default '{}',

  -- Author. Snapshot the email so the row stays readable if the user is
  -- later deleted (mirrors the Phase 1 task-history pattern).
  created_by_id     uuid references public.users(id) on delete set null,
  created_by_email  text,

  -- Provenance. FK to the extensible source lookup.
  source            text not null default 'manual'
                    references public.hq_memory_sources(slug),

  visibility        text not null default 'public_hq'
                    check (visibility in (
                      'public_hq',   -- any AI employee / HQ operator
                      'department',  -- same-department employees only
                      'private',     -- author + explicit grants only
                      'restricted',  -- explicit grants only (see grants table)
                      'system'       -- engine-internal; not surfaced to AI
                    )),

  -- Optional customer-org association. Denormalised snapshot — NOT an FK
  -- into tenant tables, to keep HQ fully decoupled from customer RLS.
  organisation_id   uuid,
  organisation_name text,

  -- RESERVED for future semantic search. Never populated or read in
  -- Phase 2 — architecture only. Kept as jsonb so we are not coupled to
  -- pgvector being enabled; a later phase can migrate this to a vector.
  embedding_placeholder jsonb,

  confidence        integer not null default 80
                    check (confidence between 0 and 100),

  status            text not null default 'active'
                    check (status in ('draft', 'active', 'archived', 'superseded')),

  version           integer not null default 1 check (version >= 1),

  pinned            boolean not null default false,

  -- Access analytics (drives "recently accessed" + dashboard).
  access_count      integer not null default 0,
  last_accessed_at  timestamp with time zone,

  -- Weighted full-text vector — generated, so it can never drift from
  -- the content. GIN-indexed below for instant search at scale.
  search_tsv        tsvector generated always as (
                      setweight(to_tsvector('english', coalesce(title, '')), 'A') ||
                      setweight(to_tsvector('english', coalesce(summary, '')), 'B') ||
                      setweight(to_tsvector('english', coalesce(body, '')), 'C')
                    ) stored,

  created_at        timestamp with time zone not null default now(),
  updated_at        timestamp with time zone not null default now()
);

alter table public.hq_memories enable row level security;
-- NO policies → service-role only. Permission-awareness (visibility +
-- grants) is enforced in the HQ-gated service layer, never via a
-- customer-reachable JWT.

-- ---------------------------------------------------------------------
-- Relationships — polymorphic links making the knowledge interconnected.
-- ---------------------------------------------------------------------

create table if not exists public.hq_memory_relationships (
  id            uuid primary key default gen_random_uuid(),
  memory_id     uuid not null references public.hq_memories(id) on delete cascade,

  entity_type   text not null check (entity_type in (
                  'feature', 'customer', 'organisation', 'github_pr',
                  'roadmap_item', 'decision', 'employee', 'bug', 'release',
                  'documentation', 'memory', 'other'
                )),
  -- Free-form reference (uuid, PR number, slug, url…). Not FK-constrained
  -- because targets span both HQ and external systems.
  entity_id     text,
  entity_label  text not null check (char_length(entity_label) between 1 and 300),
  relation      text not null default 'related_to' check (char_length(relation) <= 60),

  created_by_email text,
  created_at    timestamp with time zone not null default now()
);

alter table public.hq_memory_relationships enable row level security;
-- NO policies → service-role only.

-- ---------------------------------------------------------------------
-- Memory <-> AI employee links. Drives the read-only per-employee feed
-- (Current / Recent / Relevant / Pinned / Department memory).
-- ---------------------------------------------------------------------

create table if not exists public.hq_memory_employee_links (
  id              uuid primary key default gen_random_uuid(),
  memory_id       uuid not null references public.hq_memories(id) on delete cascade,
  ai_employee_id  uuid not null references public.ai_employees(id) on delete cascade,
  link_kind       text not null default 'relevant'
                  check (link_kind in ('relevant', 'pinned', 'owner', 'contributor')),
  created_by_email text,
  created_at      timestamp with time zone not null default now(),
  unique (memory_id, ai_employee_id, link_kind)
);

alter table public.hq_memory_employee_links enable row level security;
-- NO policies → service-role only.

-- ---------------------------------------------------------------------
-- Access grants — back 'restricted'/'private' visibility with explicit,
-- reusable permissions (a department or a specific employee).
-- ---------------------------------------------------------------------

create table if not exists public.hq_memory_access_grants (
  id            uuid primary key default gen_random_uuid(),
  memory_id     uuid not null references public.hq_memories(id) on delete cascade,
  grantee_type  text not null check (grantee_type in ('department', 'employee')),
  -- department slug (e.g. 'engineering') or an ai_employee_id uuid string.
  grantee_value text not null check (char_length(grantee_value) between 1 and 100),
  created_by_email text,
  created_at    timestamp with time zone not null default now(),
  unique (memory_id, grantee_type, grantee_value)
);

alter table public.hq_memory_access_grants enable row level security;
-- NO policies → service-role only.

-- ---------------------------------------------------------------------
-- Events — the per-memory timeline. Captures human edits AND AI/system
-- reads (too high-volume for the global admin_activity_log). Mutating
-- HQ actions also write to admin_activity_log for the company-wide audit.
-- ---------------------------------------------------------------------

create table if not exists public.hq_memory_events (
  id              uuid primary key default gen_random_uuid(),
  memory_id       uuid not null references public.hq_memories(id) on delete cascade,
  event_type      text not null check (event_type in (
                    'created', 'updated', 'viewed', 'ai_accessed',
                    'status_changed', 'pinned', 'unpinned', 'linked',
                    'unlinked', 'version_restored'
                  )),
  actor_email     text,  -- human actor; null for AI / system events
  ai_employee_id  uuid references public.ai_employees(id) on delete set null,
  detail          jsonb,
  created_at      timestamp with time zone not null default now()
);

alter table public.hq_memory_events enable row level security;
-- NO policies → service-role only.

-- ---------------------------------------------------------------------
-- Versions — immutable snapshots for full version history.
-- ---------------------------------------------------------------------

create table if not exists public.hq_memory_versions (
  id              uuid primary key default gen_random_uuid(),
  memory_id       uuid not null references public.hq_memories(id) on delete cascade,
  version         integer not null,
  title           text not null,
  summary         text not null default '',
  body            text not null default '',
  memory_type     text,
  department      text,
  importance      text,
  tags            text[] not null default '{}',
  status          text,
  edited_by_email text,
  created_at      timestamp with time zone not null default now(),
  unique (memory_id, version)
);

alter table public.hq_memory_versions enable row level security;
-- NO policies → service-role only.

-- ---------------------------------------------------------------------
-- Indexes — built for instant search + the dashboard at millions of rows.
-- ---------------------------------------------------------------------

-- Full-text search (GIN over the weighted, generated tsvector).
create index if not exists hq_memories_search_idx
  on public.hq_memories using gin (search_tsv);

-- Tag filtering / topic grouping.
create index if not exists hq_memories_tags_idx
  on public.hq_memories using gin (tags);

-- Common filter facets.
create index if not exists hq_memories_type_idx        on public.hq_memories (memory_type);
create index if not exists hq_memories_department_idx  on public.hq_memories (department);
create index if not exists hq_memories_status_idx      on public.hq_memories (status);
create index if not exists hq_memories_importance_idx  on public.hq_memories (importance);
create index if not exists hq_memories_visibility_idx  on public.hq_memories (visibility);
create index if not exists hq_memories_created_idx     on public.hq_memories (created_at desc);
create index if not exists hq_memories_accessed_idx    on public.hq_memories (last_accessed_at desc nulls last);
create index if not exists hq_memories_created_by_idx  on public.hq_memories (created_by_email);

-- Partial indexes for the hottest dashboard reads.
create index if not exists hq_memories_pinned_idx
  on public.hq_memories (updated_at desc) where pinned = true;
create index if not exists hq_memories_org_idx
  on public.hq_memories (organisation_id) where organisation_id is not null;

-- Child-table foreign-key lookups.
create index if not exists hq_mem_rel_memory_idx    on public.hq_memory_relationships (memory_id);
create index if not exists hq_mem_rel_entity_idx    on public.hq_memory_relationships (entity_type, entity_id);
create index if not exists hq_mem_emp_memory_idx    on public.hq_memory_employee_links (memory_id);
create index if not exists hq_mem_emp_employee_idx  on public.hq_memory_employee_links (ai_employee_id, link_kind);
create index if not exists hq_mem_grant_memory_idx  on public.hq_memory_access_grants (memory_id);
create index if not exists hq_mem_grant_lookup_idx  on public.hq_memory_access_grants (grantee_type, grantee_value);
create index if not exists hq_mem_events_memory_idx on public.hq_memory_events (memory_id, created_at desc);
create index if not exists hq_mem_versions_memory_idx on public.hq_memory_versions (memory_id, version desc);

-- ---------------------------------------------------------------------
-- updated_at touch trigger for hq_memories.
-- ---------------------------------------------------------------------

create or replace function public._hq_memories_touch()
returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end $$;

drop trigger if exists hq_memories_touch on public.hq_memories;
create trigger hq_memories_touch
  before update on public.hq_memories
  for each row execute function public._hq_memories_touch();
