-- CrewFlow HQ — Alerts + AI COO (HQ-5).
--
-- The alerts list is generated by a DETERMINISTIC rules engine
-- (lib/hq/alert-rules.ts) against the existing org / billing /
-- import / demo tables. No LLM, no separate signals pipeline — the
-- engine is pure and re-runs on every page load.
--
-- This migration adds ONE small table — `admin_alert_state` —
-- which carries the operator-managed lifecycle bits the rules
-- engine itself can't derive: was this alert read, snoozed,
-- resolved, assigned to someone?
--
-- Key shape choices:
--   * Keyed by (rule_id, org_id). The rules engine is responsible
--     for ensuring rule_id is stable so the state row survives
--     across re-runs.
--   * No row needed until the operator interacts. A fresh-fired
--     alert has zero state by default; LEFT JOIN handles missing.
--   * Resolved alerts are auto-archived from the default view (the
--     UI filters where resolved_at IS NULL unless ?show=resolved).
--   * Service-role only (no RLS policies). Access mediated through
--     /admin/* pages gated by isSuperAdminEmail.

create table if not exists public.admin_alert_state (
  id              uuid primary key default gen_random_uuid(),
  -- Stable identifier from the rules engine ('failed_payment',
  -- 'migration_stalled', etc). Matches the AlertRuleId union in
  -- lib/hq/alert-rules.ts.
  rule_id         text not null,
  org_id          uuid not null references public.organizations(id) on delete cascade,

  -- Lifecycle stamps. NULL means the operator hasn't touched it.
  read_at         timestamp with time zone,
  snoozed_until   timestamp with time zone,
  resolved_at     timestamp with time zone,

  -- Who's chasing this. Null = unassigned (the COO will pick it up).
  assigned_to     uuid references public.users(id) on delete set null,

  -- Optional note the operator can leave on resolve/snooze.
  resolution_note text,

  -- Audit + the user who last touched this row.
  created_by      uuid references public.users(id) on delete set null,
  created_at      timestamp with time zone not null default now(),
  updated_at      timestamp with time zone not null default now(),

  -- One state row per (rule, org). UPSERT on conflict.
  unique (rule_id, org_id)
);

alter table public.admin_alert_state enable row level security;
-- No policies → service-role only.

-- Fast lookup for the alerts list page (everything for an org or
-- everything that's still active).
create index if not exists admin_alert_state_org_idx
  on public.admin_alert_state (org_id, rule_id);

-- The default list view filters where resolved_at IS NULL — index
-- the open set so the page query stays cheap as the table grows.
create index if not exists admin_alert_state_open_idx
  on public.admin_alert_state (rule_id, org_id)
  where resolved_at is null;

-- Assigned-to-me queries (a future "my queue" filter).
create index if not exists admin_alert_state_assignee_idx
  on public.admin_alert_state (assigned_to, resolved_at)
  where assigned_to is not null;

-- Touch trigger keeps updated_at honest.
create or replace function public._admin_alert_state_touch()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists admin_alert_state_touch on public.admin_alert_state;
create trigger admin_alert_state_touch
  before update on public.admin_alert_state
  for each row execute function public._admin_alert_state_touch();
